# Generated by Django 4.2.7 on 2023-11-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Архив'),
        ),
    ]
